server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index signup.html;
    }

    location ~ \.php$ {
        root /usr/share/nginx/html;
        fastcgi_pass app:9000;
        fastcgi_index submit.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/submit.php;
    }
}